---
apiVersion: v1
kind: Service
metadata:
  name: seerr
  namespace: media
spec:
  ports:
    - port: 5055
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: seerr
