apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
    - ./crowdsec/ks.yaml
    - flux-alerts
    - kube-prometheus-stack
    - ./librenms/ks.yaml
    - smokeping
    - unifi-poller
