---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: mariadb-operator-charts
  namespace: flux-system
spec:
  interval: 30m
  url: https://helm.mariadb.com/mariadb-operator
  timeout: 3m
