---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager.yaml
  - cnpg.yaml
  - mariadb-operator.yaml
  - metallb-system.yaml
  - monitoring.yaml
  - networking.yaml
  - trivy-system.yaml
  - woodpecker.yaml
