---
apiVersion: v1
kind: Service
metadata:
  name: smtp-relay
  namespace: networking
  labels:
    app: smtp-relay
spec:
  type: LoadBalancer
  loadBalancerIP: 172.16.38.225
  selector:
    app: smtp-relay
  ports:
    - name: smtp
      port: 25
      targetPort: smtp
      protocol: TCP
