---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - mariadb-galera-secret.sops.yaml
  - mariadb-galera.yaml
  - mariadb-galera-servicemonitor.yaml
  - homeassistant.yaml
  - librenms.yaml
  - uptime-kuma.yaml
  - backup.yaml
