---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - secret.sops.yaml
  - pvc.yaml
  - helm-release.yaml
  - cronjob.yaml
  - mariadb-galera-secret.sops.yaml
  - mariadb-galera.yaml
  - mariadb-galera-servicemonitor.yaml
  - mariadb-galera-backup.yaml