---
apiVersion: v1
kind: ConfigMap
metadata:
  name: zigbee2mqtt-settings
  namespace: default
data:
  configuration.yaml: |
    homeassistant: false
    permit_join: true
    frontend:
      port: 8080
    mqtt:
      base_topic: zigbee2mqtt
      include_device_information: true
      server: mqtt://localhost
    serial:
      adapter: zstack
      baudrate: 115200
      port: tcp://SLZB-06P7.lab.${SECRET_LAB_DOMAIN}:6638
    advanced:
      homeassistant_discovery_topic: homeassistant
      homeassistant_status_topic: homeassistant/status
      last_seen: ISO_8601
      log_level: info
      log_output:
        - console
      network_key: GENERATE
      transmit_power: 20
    experimental:
      new_api: true
