---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cluster.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - secrets.sops.yaml
  - redis-deployment.yaml
  - backup.yaml
  - podmonitor.yaml
