---
apiVersion: v1
kind: Service
metadata:
  name: dawarich-app
  namespace: default
  labels:
    app: dawarich
    component: app
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: dawarich
    component: app
