---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: bgp-address-pool
  namespace: metallb-system
spec:
  addresses:
    - "${METALLB_LB_RANGE}"
---
apiVersion: metallb.io/v1beta1
kind: BFDProfile
metadata:
  name: bfd-profile
  namespace: metallb-system
spec:
  receiveInterval: 380
  transmitInterval: 270
---
apiVersion: metallb.io/v1beta2
kind: BGPPeer
metadata:
  name: bgp-k3s-cgn
  namespace: metallb-system
spec:
  myASN: 65123
  peerASN: 65123
  peerAddress: 10.0.0.1
  bfdProfile: bfd-profile
---
apiVersion: metallb.io/v1beta2
kind: BGPPeer
metadata:
  name: bgp-k3s-hel1
  namespace: metallb-system
spec:
  myASN: 65123
  peerASN: 65123
  peerAddress: 10.10.0.1
  bfdProfile: bfd-profile
---
apiVersion: metallb.io/v1beta1
kind: BGPAdvertisement
metadata:
  name: bgp-advertisement
  namespace: metallb-system
spec:
  ipAddressPools:
    - bgp-address-pool
