---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: searxng
  namespace: default
  annotations:
    hajimari.io/appName: "SearxNG"
    hajimari.io/enable: "true"
    hajimari.io/icon: "search"
    external-dns.alpha.kubernetes.io/target: "${SECRET_CLOUDFLARE_TUNNEL_DOMAIN}"
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
    traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
    traefik.ingress.kubernetes.io/router.middlewares: "networking-cloudflarewarp@kubernetescrd"
    traefik.ingress.kubernetes.io/service.serversscheme: "http"
    external-dns/external: "true"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - "s.${SECRET_LAB_DOMAIN}"
        - "search.${SECRET_LAB_DOMAIN}"
      secretName: "${SECRET_LAB_DOMAIN/./-}-tls"
  rules:
    - host: "s.${SECRET_LAB_DOMAIN}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: searxng
                port:
                  name: http
    - host: "search.${SECRET_LAB_DOMAIN}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: searxng
                port:
                  name: http
