---
kind: Endpoints
apiVersion: v1
metadata:
  name: garage-proxy
  namespace: networking
subsets:
  - addresses:
      - ip: 10.0.0.25
    ports:
      - name: http
        port: 30188
---
kind: Service
apiVersion: v1
metadata:
  name: garage-proxy
  namespace: networking
spec:
  ports:
    - name: http
      protocol: TCP
      port: 30188
      targetPort: 30188
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: garage-proxy
  namespace: networking
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"
    hajimari.io/appName: "Garage"
    hajimari.io/enable: "true"
    hajimari.io/icon: "server"
    traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
    traefik.ingress.kubernetes.io/service.serversscheme: "http"
    external-dns/internal: "true"
spec:
  ingressClassName: traefik-internal
  tls:
    - hosts:
        - "*.s3.${SECRET_LAB_DOMAIN}"
        - "s3.${SECRET_LAB_DOMAIN}"
      secretName: "s3-${SECRET_LAB_DOMAIN/./-}-tls"
  rules:
    - host: "s3.${SECRET_LAB_DOMAIN}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: garage-proxy
                port:
                  number: 30188
    - host: "*.s3.${SECRET_LAB_DOMAIN}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: garage-proxy
                port:
                  number: 30188
