---
kind: Endpoints
apiVersion: v1
metadata:
  name: searxng-proxy
  namespace: networking
subsets:
  - addresses:
      - ip: 10.0.50.232
    ports:
      - name: http
        port: 8888
---
kind: Service
apiVersion: v1
metadata:
  name: searxng-proxy
  namespace: networking
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8888
      targetPort: 8888
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: searxng-proxy
  namespace: networking
  annotations:
    hajimari.io/appName: "SearxNG"
    hajimari.io/enable: "true"
    hajimari.io/icon: "search"
    external-dns.alpha.kubernetes.io/target: "${SECRET_CLOUDFLARE_TUNNEL_DOMAIN}"
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
    traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
    traefik.ingress.kubernetes.io/router.middlewares: "networking-cloudflarewarp@kubernetescrd"
    traefik.ingress.kubernetes.io/service.serversscheme: "http"
    external-dns/external: "true"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - "s.${SECRET_LAB_DOMAIN}"
        - "search.${SECRET_LAB_DOMAIN}"
      secretName: "${SECRET_LAB_DOMAIN/./-}-tls"
  rules:
    - host: "s.${SECRET_LAB_DOMAIN}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: searxng-proxy
                port:
                  name: http
    - host: "search.${SECRET_LAB_DOMAIN}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: searxng-proxy
                port:
                  name: http
